question_data = [
    {"category": "General Knowledge", "type": "multiple", "difficulty": "easy",
     "question": "What is the first book of the Old Testament?", "correct_answer": "Genesis",
     "incorrect_answers": ["Exodus", "Leviticus", "Numbers"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "Who is the main character in &quot;The Stanley Parable&quot;?", "correct_answer": "Stanley",
     "incorrect_answers": ["The Adventure Line", "The Narrator", "The Boss"]},
    {"category": "Entertainment: Books", "type": "multiple", "difficulty": "easy",
     "question": "Under what pseudonym did Stephen King publish five novels between 1977 and 1984?",
     "correct_answer": "Richard Bachman", "incorrect_answers": ["J. D. Robb", "Mark Twain", "Lewis Carroll"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "medium",
     "question": "In Call of Duty: United Offensive, what two soldiers share a name of a video game character?",
     "correct_answer": "Gordon &amp; Freeman",
     "incorrect_answers": ["Sam &amp; Fisher", "Nathan &amp; Drake", "Dig &amp; Dug"]},
    {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
     "question": "Kissing someone for one minute burns about 2 calories.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Sports", "type": "multiple", "difficulty": "medium",
                                       "question": "Which car manufacturer won the 2016 24 Hours of Le Mans?",
                                       "correct_answer": "Porsche", "incorrect_answers": ["Toyota", "Audi", "Ferrari"]},
    {"category": "General Knowledge", "type": "multiple", "difficulty": "medium",
     "question": "Which iconic Disneyland attraction was closed in 2017 to be remodeled as a &quot;Guardians of the Galaxy&quot; themed ride?",
     "correct_answer": "Twilight Zone Tower of Terror",
     "incorrect_answers": ["The Haunted Mansion", "Pirates of the Caribbean", "Peter Pan&#039;s Flight"]},
    {"category": "History", "type": "multiple", "difficulty": "hard",
     "question": "How long did the Warsaw Uprising during World War II last?", "correct_answer": "63 Days",
     "incorrect_answers": ["20 Days", "55 Days", "224 Days"]},
    {"category": "Entertainment: Video Games", "type": "multiple", "difficulty": "easy",
     "question": "In &quot;PUBATTLEGROUNDS&quot; which ammo type does the M24 use?", "correct_answer": "7.62mm",
     "incorrect_answers": ["5.56mm", "9mm", ".300 Magnum"]},
    {"category": "Science & Nature", "type": "multiple", "difficulty": "medium",
     "question": "Deionized water is water with which of the following removed?", "correct_answer": "Iron",
     "incorrect_answers": ["Oxygen", "Hydrogen", "Uncharged atoms"]}]
